= Transaction Fraud Ring

== 1. Introduction

A transaction fraud ring refers to a group of people collaborating to engage in fraudulent activities, like transferring funds through multiple accounts. These rings work across different locations and employ diverse strategies to evade detection. It is critical for financial organisations to detect these rings, especially with enhancement to Contingent Reimbursement Model (CRM).

== 2. Scenario

The requirement for financial institutes to implement and stop transaction fraud has been around for many years and is core to many regulations. 

One example of this is enhancements that are being made to protect customers from Authorised Push Payment scams. The UK has increased customer protection and placed a more significant responsibility on financial institutions to help mitigate these scams. 

One of the fastest-growing scams is the Authorised Push Payment (APP) fraud. It resulted in a loss of over *£249 million in the first half of 2022*, a 30% increase compared to the same period in 2020. Reference

Understanding fraudulent behaviour inside your network is one of many ways to help mitigate these scams, as you can identify fraudulent accounts inside your banking estate.

== 3. Solution

Neo4j offer an improved method of uncovering transaction fraud rings and other sophisticated scams with a high degree of accuracy and is capable of stopping advanced fraud scenarios in real-time.

=== How Graph Databases Can Help?

Implementing Neo4j can help execute analysis that was not previously possible. Examples of the scenarios are:

* Execute ring-based queries to follow transactions as they are sent to both internal and external beneficiaries.
* In real-time, perform advanced analytics on the transaction rings to understand patterns.
* Understand common exit and entry accounts in possible fraudulent activities.

== 4. Modelling

This section will show examples of cypher queries on an example graph. The intention is to illustrate what the queries look like and provide a guide on how to structure your data in a real setting. We will do this on a small transaction network graph of several nodes connected in a ring structure.

The example graph will be based on the data model below:

=== 4.1. Transaction Modelled as Relationship

==== 4.1.1 Detailed Documentation

xref:finserv/retail-banking/transaction-ring/transaction-ring-relationship-version.adoc[]

==== 4.1.2 Data Model

image::finserv/fs-transaction-ring-data-relationship-version-model.svg[]

=== 4.2 Transaction Modelled as Node

==== 4.2.1 Detailed Documentation

xref:finserv/retail-banking/transaction-ring/transaction-ring-node-version.adoc[]

==== 4.2.2 Data Model

image::finserv/fs-transaction-ring-data-node-version-model.svg[]